import{a as b,S as v,i as l}from"./assets/vendor-1AYLTIiv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&a(p)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const x="50629766-ca4e4f15305d377d5e3228fef",S="https://pixabay.com/api/";function m(o,t=1,r=15){const a={key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r};return b.get(S,{params:a}).then(e=>{if(e.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return e.data})}let u;const h=document.querySelector(".gallery"),g=document.querySelector(".loader");function y(o){const t=o.map(r=>`
        <li class="gallery-item">
            <a href="${r.largeImageURL}">
                <img src="${r.webformatURL}" alt="${r.tags}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${r.likes}</span></p>
                <p class="text">Views <span class="span">${r.views}</span></p>
                <p class="text">Comments <span class="span">${r.comments}</span></p>
                <p class="text">Downloads <span class="span">${r.downloads}</span></p>
            </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function q(){h.innerHTML=""}function L(){g.style.display="block"}function w(){g.style.display="none"}const P=document.querySelector(".form");document.querySelector(".gallery");const c=document.querySelector(".load-more");let i="",n=1;const d=15;let f=0;P.addEventListener("submit",o=>{if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){l.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}n=1,q(),L(),c.classList.add("is-hidden"),m(i,n,d).then(t=>{const{hits:r,totalHits:a}=t;f=a,y(r),f>d&&c.classList.remove("is-hidden")}).catch(t=>{l.error({title:"Error",message:t.message||"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{w()})});c.addEventListener("click",()=>{n+=1,L(),m(i,n,d).then(o=>{y(o.hits);const t=Math.ceil(f/d);n>=t&&(c.classList.add("is-hidden"),l.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"}))}).catch(o=>{l.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}).finally(()=>{w()})});
//# sourceMappingURL=index.js.map
